slug: training
title: Technical Training
summary: Hands-on training for operators and maintenance teams—alignment, lubrication, inspection, and safe work procedures.
bullets:
  - Alignment fundamentals and laser alignment demos
  - Bearing handling, lubrication, and failure signs
  - Preventive checks and documentation
  - Safety (LOTO) and equipment care
hero: /images/services/training/hero.jpg
alt: Technical training session for plant maintenance
tags: [training, capacity-building]
